# Generated by Django 3.1.6 on 2021-12-12 07:48

import apps.sales.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedBackValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Оценка в отзыве')),
            ],
            options={
                'verbose_name': 'Оценка отзыва',
                'verbose_name_plural': 'Оценки для отзывов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование квеста')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=150, verbose_name='Описание квеста')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.sales.models.upload_path_quest_photo, verbose_name='Фото')),
                ('duration', models.DurationField(verbose_name='Длительность квеста')),
                ('difficulty', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность квеста')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена квеста')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование статуса')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TypeQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип квеста',
                'verbose_name_plural': 'Типы квеста',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuestFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание типа')),
                ('feedback_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_value', to='sales.feedbackvalue', verbose_name='Оценка отзыва')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='sales.quest', verbose_name='Отзыв о квесте')),
            ],
            options={
                'verbose_name': 'Отзыв квеста',
                'verbose_name_plural': 'Отзывы квеста',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='sales.typequest', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Комментарий к заказу')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подвержден?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('time_start', models.DateTimeField(verbose_name='Дата\\Время старта')),
                ('time_finish', models.DateTimeField(verbose_name='Дата\\Время окончания')),
                ('count_players', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество игроков')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказ Пользователя')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='sales.coupon', verbose_name='Купон')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='account.manager', verbose_name='Менеджер')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest', to='sales.quest', verbose_name='Квест')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='sales.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('id',),
            },
        ),
    ]
