# Generated by Django 3.1.6 on 2021-12-06 13:29

import apps.sales.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20211205_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typequest',
            options={'ordering': ('name',), 'verbose_name': 'Тип квеста', 'verbose_name_plural': 'Типы квеста'},
        ),
        migrations.AddField(
            model_name='quest',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.sales.models.upload_path_quest_photo, verbose_name='Фото'),
        ),
    ]
