# Generated by Django 3.1.6 on 2021-12-09 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20211206_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность квеста'),
        ),
    ]
