# Generated by Django 3.1.6 on 2021-12-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quest_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=5, verbose_name='Оценка в отзыве')),
            ],
            options={
                'verbose_name': 'Оценка отзыва',
                'verbose_name_plural': 'Оценки для отзывов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание типа')),
                ('feedback_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_value', to='sales.feedbackvalue', verbose_name='Оценка отзыва')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='sales.quest', verbose_name='Отзыв о квесте')),
            ],
            options={
                'verbose_name': 'Отзыв квеста',
                'verbose_name_plural': 'Отзывы квеста',
                'ordering': ('id',),
            },
        ),
    ]
