# Generated by Django 3.1.6 on 2021-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_feedbackvalue_questfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackvalue',
            name='value',
            field=models.IntegerField(verbose_name='Оценка в отзыве'),
        ),
        migrations.AlterField(
            model_name='questfeedback',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание типа'),
        ),
    ]
