# Generated by Django 3.1.6 on 2021-12-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20211209_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quests',
        ),
        migrations.AddField(
            model_name='order',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest', to='sales.quest', verbose_name='Квест'),
        ),
    ]
