# Generated by Django 3.1.6 on 2021-12-12 13:42

import apps.content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Оценка в отзыве')),
            ],
            options={
                'verbose_name': 'Оценка отзыва',
                'verbose_name_plural': 'Оценки для отзывов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование квеста')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=150, verbose_name='Описание квеста')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.content.models.upload_path_quest_photo, verbose_name='Фото')),
                ('duration', models.DurationField(verbose_name='Длительность квеста')),
                ('difficulty', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность квеста')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена квеста')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TypeQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип квеста',
                'verbose_name_plural': 'Типы квеста',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuestFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Отзыв')),
                ('feedback_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_value', to='content.feedbackvalue', verbose_name='Оценка отзыва')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='content.quest', verbose_name='Отзыв о квесте')),
            ],
            options={
                'verbose_name': 'Отзыв квеста',
                'verbose_name_plural': 'Отзывы квеста',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='content.typequest', verbose_name='Тип'),
        ),
    ]
